- name: install Homebrew Casks
  community.general.homebrew_cask:
    name: 
      - docker
      - brave-browser
      - httpie
      - kitty
      - visual-studio-code
  tags:
    - install
    - apps
