- name: Install System Packages
  community.general.homebrew:
    name: 
      - git
      - tmux
      - fzf
      - ripgrep
      - tldr
      - fd
      - gh
      - httpie
      - direnv
      - pyenv
      - go
      - duckdb
      - neovim
      - jq
      - ruff
    state: present
  tags:
    - install
    - core

- name: Install Python build dependencies
  community.general.homebrew:
    name: 
      - duckdb
      - openssl
      - readline
      - sqlite3
      - xz
      - zlib
      - tcl-tk
    state: present
  tags:
    - install
    - python

- name: Init fzf
  shell: yes | $(brew --prefix)/opt/fzf/install

- name: Install nvm
  ansible.builtin.shell: >
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
  args:
    creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"
  tags:
    - install
    - node

- name: Install poetry
  shell: curl -sSL https://install.python-poetry.org | python3 -
  tags:
    - install
    - python
      
- name: Install Rust
  shell: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --no-modify-path -y
  tags:
    - install
    - rust
