- name: Add Brew Taps
  community.general.homebrew_tap:
    name: 
      - FelixKratz/formulae # Sketchybar
      - homebrew/cask-fonts # Hack Nerd Fonts
  tags:
    - install
    - workspace

- name: Install workspace services
  community.general.homebrew:
    name: 
      - koekeishiya/formulae/yabai
      - koekeishiya/formulae/skhd
      - sketchybar
  tags:
    - install
    - workspace

- name: Install Fonts (1)
  ansible.builtin.copy:
    src: "{{ dotfiles }}/personal/fonts/"
    dest: ~/Library/Fonts/
  tags:
    - fonts
    - install
    
- name: Install Fonts (2)
  community.general.homebrew_cask:
    name: 
      - font-hack-nerd-font
      - sf-symbols # San Fransico (Apple) symbols
  tags:
    - fonts
    - install

- name: Install Fonts (3)
  shell: curl -L https://github.com/kvndrsslr/sketchybar-app-font/releases/download/v1.0.3/sketchybar-app-font.ttf -o $HOME/Library/Fonts/sketchybar-app-font.ttf
  tags:
    - fonts
    - install

- name: Create yabai digest
  shell: shasum -a 256 $(which yabai)
  # Must use the brew --prefix as "which yabai" is just a simlink
  # shell: shasum -a 256 "$(brew --prefix yabai)/bin/yabai"
  register: yabai_digest
  tags:
    - workspace
    - yabai
    - sudoers


- name: Add yabai to sudoers 
  community.general.sudoers:
    name: yabai 
    user: "{{ lookup('env', 'USER') }}"
    runas: root
    commands: "sha256:{{ yabai_digest.stdout }} --load-sa"
    sudoers_path: /private/etc/sudoers.d
  become: yes
  tags:
    - workspace
    - yabai
    - sudoers

- name: start services
  ansible.builtin.shell: |
    brew services start yabai 
    brew services start skhd
    brew services start sketchybar
  tags:
    - workspace
    - services

- name: Cloning tmux package manager 
  ansible.builtin.git:
    repo: 'https://github.com/tmux-plugins/tpm'
    dest: '~/.tmux/plugins/tpm'
    update: yes
    accept_hostkey: yes
    version: main
  tags:
    - workspace
    - tmux 
